package util

var Mp map[string][]string = map[string][]string{
	" ":  []string{" "},
	"　":  []string{" "},
	".":  []string{"."},
	"。":  []string{"."},
	"、":  []string{","},
	",":  []string{","},
	"-":  []string{"-"},
	"ー":  []string{"-"},
	"~":  []string{"~"},
	"～":  []string{"~"},
	"=":  []string{"="},
	"＝":  []string{"="},
	"/":  []string{"/"},
	"%":  []string{"%"},
	"(":  []string{"("},
	")":  []string{")"},
	"0":  []string{"0"},
	"1":  []string{"1"},
	"2":  []string{"2"},
	"3":  []string{"3"},
	"4":  []string{"4"},
	"5":  []string{"5"},
	"6":  []string{"6"},
	"7":  []string{"7"},
	"8":  []string{"8"},
	"9":  []string{"9"},
	"A":  []string{"A", "a"},
	"a":  []string{"a"},
	"B":  []string{"B", "b"},
	"b":  []string{"b"},
	"C":  []string{"C", "c"},
	"c":  []string{"c"},
	"D":  []string{"D", "d"},
	"d":  []string{"d"},
	"E":  []string{"E", "e"},
	"e":  []string{"e"},
	"F":  []string{"F", "f"},
	"f":  []string{"f"},
	"G":  []string{"G", "g"},
	"g":  []string{"g"},
	"H":  []string{"H", "h"},
	"h":  []string{"h"},
	"I":  []string{"I", "i"},
	"i":  []string{"i"},
	"J":  []string{"J", "j"},
	"j":  []string{"j"},
	"K":  []string{"K", "k"},
	"k":  []string{"k"},
	"L":  []string{"L", "l"},
	"l":  []string{"l"},
	"M":  []string{"M", "m"},
	"m":  []string{"m"},
	"N":  []string{"N", "n"},
	"n":  []string{"n"},
	"O":  []string{"O", "o"},
	"o":  []string{"o"},
	"P":  []string{"P", "p"},
	"p":  []string{"p"},
	"Q":  []string{"Q", "q"},
	"q":  []string{"q"},
	"R":  []string{"R", "r"},
	"r":  []string{"r"},
	"S":  []string{"S", "s"},
	"s":  []string{"s"},
	"T":  []string{"T", "t"},
	"t":  []string{"t"},
	"U":  []string{"U", "u"},
	"u":  []string{"u"},
	"V":  []string{"V", "v"},
	"v":  []string{"v"},
	"W":  []string{"W", "w"},
	"w":  []string{"w"},
	"X":  []string{"X", "x"},
	"x":  []string{"x"},
	"Y":  []string{"Y", "y"},
	"y":  []string{"y"},
	"Z":  []string{"Z", "z"},
	"z":  []string{"z"},
	"あ":  []string{"a"},
	"ぁ":  []string{"la", "xa"},
	"うぁ": []string{"wha"},
	"い":  []string{"i", "yi"},
	"ぃ":  []string{"li", "xi", "lyi", "xyi"},
	"うぃ": []string{"wi", "whi"},
	"う":  []string{"u", "wu", "whu"},
	"ぅ":  []string{"lu", "xu"},
	"え":  []string{"e"},
	"ぇ":  []string{"le", "xe", "lye", "xye"},
	"いぇ": []string{"ye"},
	"うぇ": []string{"we", "whe"},
	"お":  []string{"o"},
	"ぉ":  []string{"lo", "xo"},
	"うぉ": []string{"who"},
	"か":  []string{"ka", "ca"},
	"ヵ":  []string{"lka", "xka"},
	"が":  []string{"ga"},
	"きゃ": []string{"kya"},
	"ぎゃ": []string{"gya"},
	"くぁ": []string{"qa", "kwa", "qwa"},
	"くゃ": []string{"qya"},
	"ぐぁ": []string{"gwa"},
	"き":  []string{"ki"},
	"ぎ":  []string{"gi"},
	"きぃ": []string{"kyi"},
	"ぎぃ": []string{"gyi"},
	"くぃ": []string{"qi", "qyi", "qwi"},
	"ぐぃ": []string{"gwi"},
	"く":  []string{"ku", "cu", "qu"},
	"ぐ":  []string{"gu"},
	"きゅ": []string{"kyu"},
	"ぎゅ": []string{"gyu"},
	"くぅ": []string{"qwu"},
	"くゅ": []string{"qyu"},
	"ぐぅ": []string{"gwu"},
	"け":  []string{"ke"},
	"ヶ":  []string{"lke", "xke"},
	"げ":  []string{"ge"},
	"きぇ": []string{"kye"},
	"ぎぇ": []string{"gye"},
	"くぇ": []string{"qe", "qye", "qwe"},
	"ぐぇ": []string{"gwe"},
	"こ":  []string{"ko", "co"},
	"ご":  []string{"go"},
	"きょ": []string{"kyo"},
	"ぎょ": []string{"gyo"},
	"くぉ": []string{"qo", "qwo"},
	"くょ": []string{"qyo"},
	"ぐぉ": []string{"gwo"},
	"さ":  []string{"sa"},
	"ざ":  []string{"za"},
	"しゃ": []string{"sya", "sha"},
	"じゃ": []string{"ja", "jya", "zya"},
	"すぁ": []string{"swa"},
	"し":  []string{"si", "ci", "shi"},
	"じ":  []string{"zi", "ji"},
	"しぃ": []string{"syi"},
	"じぃ": []string{"jyi", "zyi"},
	"すぃ": []string{"swi"},
	"す":  []string{"su"},
	"ず":  []string{"zu"},
	"しゅ": []string{"syu", "shu"},
	"じゅ": []string{"ju", "jyu", "zyu"},
	"すぅ": []string{"swu"},
	"せ":  []string{"se", "ce"},
	"ぜ":  []string{"ze"},
	"しぇ": []string{"sye", "she"},
	"じぇ": []string{"je", "jye", "zye"},
	"すぇ": []string{"swe"},
	"そ":  []string{"so"},
	"ぞ":  []string{"zo"},
	"しょ": []string{"syo", "sho"},
	"じょ": []string{"jo", "jyo", "zyo"},
	"すぉ": []string{"swo"},
	"た":  []string{"ta"},
	"だ":  []string{"da"},
	"ちゃ": []string{"tya", "cha", "cya"},
	"ぢゃ": []string{"dya"},
	"つぁ": []string{"tsa"},
	"てゃ": []string{"tha"},
	"でゃ": []string{"dha"},
	"とぁ": []string{"twa"},
	"どぁ": []string{"dwa"},
	"ち":  []string{"ti", "chi"},
	"ぢ":  []string{"di"},
	"ちぃ": []string{"tyi", "cyi"},
	"ぢぃ": []string{"dyi"},
	"つぃ": []string{"tsi"},
	"てぃ": []string{"thi"},
	"でぃ": []string{"dhi"},
	"とぃ": []string{"twi"},
	"どぃ": []string{"dwi"},
	"つ":  []string{"tu", "tsu"},
	"っ":  []string{"ltu", "xtu", "ltsu", "xtsu"},
	"づ":  []string{"du"},
	"ちゅ": []string{"tyu", "chu", "cyu"},
	"ぢゅ": []string{"dyu"},
	"てゅ": []string{"thu"},
	"でゅ": []string{"dhu"},
	"とぅ": []string{"twu"},
	"どぅ": []string{"dwu"},
	"て":  []string{"te"},
	"で":  []string{"de"},
	"ちぇ": []string{"tye", "che", "cye"},
	"ぢぇ": []string{"dye"},
	"つぇ": []string{"tse"},
	"てぇ": []string{"the"},
	"でぇ": []string{"dhe"},
	"とぇ": []string{"twe"},
	"どぇ": []string{"dwe"},
	"と":  []string{"to"},
	"ど":  []string{"do"},
	"ちょ": []string{"tyo", "cho", "cyo"},
	"ぢょ": []string{"dyo"},
	"つぉ": []string{"tso"},
	"てょ": []string{"tho"},
	"でょ": []string{"dho"},
	"とぉ": []string{"two"},
	"どぉ": []string{"dwo"},
	"な":  []string{"na"},
	"にゃ": []string{"nya"},
	"に":  []string{"ni"},
	"にぃ": []string{"nyi"},
	"ぬ":  []string{"nu"},
	"にゅ": []string{"nyu"},
	"ね":  []string{"ne"},
	"にぇ": []string{"nye"},
	"の":  []string{"no"},
	"にょ": []string{"nyo"},
	"は":  []string{"ha"},
	"ば":  []string{"ba"},
	"ぱ":  []string{"pa"},
	"ひゃ": []string{"hya"},
	"びゃ": []string{"bya"},
	"ぴゃ": []string{"pya"},
	"ふぁ": []string{"fa", "fwa"},
	"ふゃ": []string{"fya"},
	"ヴぁ": []string{"va"},
	"ヴゃ": []string{"vya"},
	"ひ":  []string{"hi"},
	"び":  []string{"bi"},
	"ぴ":  []string{"pi"},
	"ひぃ": []string{"hyi"},
	"びぃ": []string{"byi"},
	"ぴぃ": []string{"pyi"},
	"ふぃ": []string{"fi", "fyi", "fwi"},
	"ヴぃ": []string{"vi", "vyi"},
	"ふ":  []string{"hu", "fu"},
	"ぶ":  []string{"bu"},
	"ぷ":  []string{"pu"},
	"ひゅ": []string{"hyu"},
	"びゅ": []string{"byu"},
	"ぴゅ": []string{"pyu"},
	"ふぅ": []string{"fwu"},
	"ふゅ": []string{"fyu"},
	"ヴ":  []string{"vu"},
	"ヴゅ": []string{"vyu"},
	"へ":  []string{"he"},
	"べ":  []string{"be"},
	"ぺ":  []string{"pe"},
	"ひぇ": []string{"hye"},
	"びぇ": []string{"bye"},
	"ぴぇ": []string{"pye"},
	"ふぇ": []string{"fe", "fye", "fwe"},
	"ヴぇ": []string{"ve", "vye"},
	"ほ":  []string{"ho"},
	"ぼ":  []string{"bo"},
	"ぽ":  []string{"po"},
	"ひょ": []string{"hyo"},
	"びょ": []string{"byo"},
	"ぴょ": []string{"pyo"},
	"ふぉ": []string{"fo", "fwo"},
	"ふょ": []string{"fyo"},
	"ヴぉ": []string{"vo"},
	"ヴょ": []string{"vyo"},
	"ま":  []string{"ma"},
	"みゃ": []string{"mya"},
	"み":  []string{"mi"},
	"みぃ": []string{"myi"},
	"む":  []string{"mu"},
	"みゅ": []string{"myu"},
	"め":  []string{"me"},
	"みぇ": []string{"mye"},
	"も":  []string{"mo"},
	"みょ": []string{"myo"},
	"や":  []string{"ya"},
	"ゃ":  []string{"lya", "xya"},
	"ゆ":  []string{"yu"},
	"ゅ":  []string{"lyu", "xyu"},
	"よ":  []string{"yo"},
	"ょ":  []string{"lyo", "xyo"},
	"ら":  []string{"ra"},
	"りゃ": []string{"rya"},
	"り":  []string{"ri"},
	"りぃ": []string{"ryi"},
	"る":  []string{"ru"},
	"りゅ": []string{"ryu"},
	"れ":  []string{"re"},
	"りぇ": []string{"rye"},
	"ろ":  []string{"ro"},
	"りょ": []string{"ryo"},
	"わ":  []string{"wa"},
	"ゎ":  []string{"lwa", "xwa"},
	"を":  []string{"wo"},
	"ん":  []string{"n", "nn", "xn"},
}
