export enum TYPES {
  LAST_PAGE_ROUTE = 'LAST_PAGE_ROUTE',
  SNACKBAR = 'SNACKBAR',
  SCROLL_TARGET = 'SCROLL_TARGET',
  SHIFT_TYPEWORD = 'SHIFT_TYPEWORD',
  SHIFT_TYPEMEANING = 'SHIFT_TYPEMEANING',
  SWITCH_CLEARED = 'SWITCH_CLEARED',
}
